const spaWhite = [
  {text:"Una maldición gitana"},
  {text:"Un minuto de silencio"},
  {text:"Muchos tornillos y pocas tuercas"},
  {text:"Un policía honesto sin nada que perder"},
  {text:"Hambruna"},
  {text:"Bacteria carnívora"},
  {text:"Víboras voladoras sexuales"},
  {text:"Que te valgan madres los países africanos"},
  {text:"Mandar mensajitos cachondos"},
  {text:"Cambia-formas"},
  {text:"Estrellas porno"},
  {text:"Violar y saquear"},
  {text:"72 vírgenes"},
  {text:"Un comando armado disparando a un domicilio"},
  {text:"Una paradoja del tiempo"},
  {text:"Antojitos mexicanos"},
  {text:"Bling bling"},
  {text:"Consultores"},
  {text:"Deuda aplastante"},
  {text:"Traumas con el papá"},
  {text:"4k pls"},
  {text:"Tirar un candelabro sobre tus enemigos mientras subes agarrado de una cuerda"},
  {text:"Potasio"},
  {text:"Desnudez frontal"},
  {text:"Inyecciones de hormonas"},
  {text:"Poner un huevo"},
  {text:"Desnudarte y ver Nickelodeon"},
  {text:"Todo"},
  {text:"Compartir jeringas"},
  {text:"Mocos"},
  {text:"La inevitable muerte del universo"},
  {text:"El milagro de dar a luz"},
  {text:"El Rapto"},
  {text:"Sacártela"},
  {text:"El privilegio de los blancos"},
  {text:"Deberes matrimoniales"},
  {text:"Un ladrón"},
  {text:"Desodorante AXE"},
  {text:"La sangre de Cristo"},
  {text:"Horrorosos accidendes de depilación láser"},
  {text:"Traps"},
  {text:"Agricultura"},
  {text:"Un mongolito robusto"},
  {text:"Selección natural"},
  {text:"Abortos con gancho de ropa"},
  {text:"Comerte tu comida antes del recreo"},
  {text:"League of Legends"},
  {text:"World of Warcraft"},
  {text:"Hacer mal tercio"},
  {text:"Obecidad"},
  {text:"Un equipo de volleybol homoerótico"},
  {text:"Tetanos"},
  {text:"Un despliegue copulatorio"},
  {text:"Torcedura testicular"},
  {text:"Buffet de pizza por $3"},
  {text:"Pizza con piña"},
  {text:"Queso fundido"},
  {text:"Ataques de velociraptor"},
  {text:"Quitarte la camiseta"},
  {text:"Esmegma"},
  {text:"Alcoholismo"},
  {text:"Un hombre de mediana edad en patines"},
  {text:"El ataque de los ositos cariñositos"},
  {text:"Atragantarse y vomitar"},
  {text:"Paletotas gigantes"},
  {text:"Odiarse a sí mismo"},
  {text:"Niños con correas"},
  {text:"Un faje sin ganas"},
  {text:"La Santa Biblia"},
  {text:"Porno alemán de fetiches"},
  {text:"Estar en llamas"},
  {text:"Embarazo adolescente"},
  {text:"Embarazo no deseado"},
  {text:"Gandhi"},
  {text:"Dejar un mensaje de voz incomodo"},
  {text:"Ganchos a la mandíbula"},
  {text:"Representantes de atención al cliente"},
  {text:"Una erección que dura más de 4 horas"},
  {text:"Mis genitales"},
  {text:"Ligar en la clínica de abortos"},
  {text:"Ciencia"},
  {text:"Sexo oral no reciproco"},
  {text:"Aves que no vuelan"},
  {text:"Una buena esnifada"},
  {text:"Gore"},
  {text:"Un desayuno balanceado"},
  {text:"Robarle un dulce a un bebé"},
  {text:"El Teletón"},
  {text:"Rascarte el trasero a escondidas"},
  {text:"Post-it pasivo-agresivos"},
  {text:"El equipo chino de gimnasia"},
  {text:"Hacerte un poco pipí"},
  {text:"Anime"},
  {text: "Reírse como una chica de anime"},
  {text:"Emisiones nocturnas"},
  {text:"Los judíos"},
  {text:"Mis caderas"},
  {text:"Muslos de acero"},
  {text:"Guiñarle a los viejitos"},
  {text:"Evadir impuestos"},
  {text:"Una caricia gentil en la entrepierna"},
  {text:"Tensión sexual"},
  {text:"La fruta prohibida"},
  {text:"Respetar a tus semejantes"},
  {text:"Whiskas®"},
  {text:"Ser rico"},
  {text:"Dulce, dulce venganza"},
  {text:"Un venado gaseoso"},
  {text:"Una sobadita"},
  {text:"Pilotos kamikaze"},
  {text:"Bob Esponja"},
  {text:"Propaganda homosexual"},
  {text:"Personas trabajadoras"},
  {text:"Un halcón con gorrito"},
  {text:"Monaguillos"},
  {text:"Dormir"},
  {text:"Enojarte tanto que se te para"},
  {text:"Muestras gratis"},
  {text:"Tanto rollo para nada"},
  {text:"Hacer lo correcto"},
  {text:"La privación de sueño"},
  {text:"Lactancia"},
  {text:"Paz mundial"},
  {text:"Masculinidad tóxica"},
  {text:"Robocop"},
  {text:"Pasado de lanza"},
  {text:"Justin Bieber"},
  {text:"Oompa-Loompas"},
  {text:"Grito de mariachi inapropiado"},
  {text:"Pubertad"},
  {text:"Fantasmas"},
  {text:"Pechos operadas asimétricos"},
  {text:"Decir adiós con las manos"},
  {text:"Dedear"},
  {text:"Yo entrando a un examen para el cual no estudie"},
  {text:"Atol con el dedo"},
  {text:"Brutalidad policiaca"},
  {text:"Una persona X"},
  {text:"Pre-adolecentes"},
  {text:"Revendedores"},
  {text:"Cobradores"},
  {text:"“Tuitear”"},
  {text:"Darth Vader"},
  {text:"Que te la jalen sin ganas"},
  {text:"Exactamente lo que esperabas"},
  {text:"Querer eructar y terminar vomitando en el suelo"},
  {text:"“Por favor”"},
  {text:"Células madre embrionarias"},
  {text:"Un escore con clase"},
  {text:"Lobotomía con picahielo"},
  {text:"Tom Cruise"},
  {text:"Herpes bucal"},
  {text:"Cachalote"},
  {text:"Gente sin casa"},
  {text:"Tercera Base"},
  {text:"Incesto"},
  {text:"Pacman tragando semen sin control"},
  {text:"Un mimo teniendo un ataque al corazón"},
  {text:"K-pop"},
  {text:"Dios"},
  {text:"Tallarse bajo los pliegues de la carne"},
  {text:"Golden shower"},
  {text:"Emociones"},
  {text:"Lamer cosas para decir que son tuyas"},
  {text:"Alergias"},
  {text:"La placenta"},
  {text:"Combustión humana espontánea"},
  {text:"Amigos con derechos"},
  {text:"Pintar con los dedos"},
  {text:"El olor de los viejitos"},
  {text:"Morirse de disentería"},
  {text:"Adorando esa vagina"},
  {text:"Mis demonios interiores"},
  {text:"Una pistola de agua llena de pipí de gato"},
  {text:"Un dictador enloquecido"},
  {text:"Acurrucarse con tu pareja"},
  {text:"¿Dónde jugaran las niñas?"},
  {text:"Peleas de gallos"},
  {text:"Fuego amigo"},
  {text:"Maldad"},
  {text:"Vomitar mariscos mientras se sangra analmente"},
  {text:"Alguna perra que ama la piña"},
  {text:"Una fiesta de cumpleaños decepcionante"},
  {text:"Una negra descarada"},
  {text:"Los gritos... los terribles gritos"},
  {text:"Mis bolas en tu cara"},
  {text:"Llamar a la policía contra un hombre negro inocente"},
  {text:"Mi fea cara y mala personalidad"},
  {text:"Atletas matemáticos"},
  {text:"Un caballo pequeño"},
  {text:"Absolutamente nadie"},
  {text:"Cabalgar hacia el atardecer"},
  {text:"Un giro de acontecimientos desafortunados"},
  {text:"Afros"},
  {text:"Destrucción mutuamente asegurada"},
  {text:"Pedófilos"},
  {text:"Levadura" },
  {text:"Robar tumbas"},
  {text:"Comerse el último bisonte que existe"},
  {text:"Catapultas"},
  {text:"Gente pobre"},
  {text:"Furries"},
  {text:"Bailar reggaetón"},
  {text:"La Fuerza"},
  {text:"Limpiarle el trasero"},
  {text:"Diseño inteligente"},
  {text:"Bocafloja"},
  {text:"Pintar con los dedos"},
  {text:"Una pistola de agua llena de pipí de gato"},
  {text:"Peleas de gallos"},
  {text:"Fuego amigo"},
  {text:"Atletas matemáticos"},
  {text:"Levadura"},
  {text:"Gente pobre"},
  {text:"Maldad"},
  {text:"Fotos de tetas"},
  {text:"Tetas falsas"},
  {text:"Diseño inteligente"},
  {text:"Super Hombres"},
  {text:"Fracaso"},
  {text:"SIDA"},
  {text:"Gladiadores Americanos"},
  {text:"Ser estúpido"},
  {text:"Cienciología"},
  {text:"Dos enanos cagando en una tina"},
  {text:"Envidia del pene"},
  {text:"El Ku Klux Klan"},
  {text:"Quitarte lo gay rezando"},
  {text:"Genghis Khan"},
  {text:"Metanfetaminas"},
  {text:"Servidumbre"},
  {text:"Cuidarse de los extraños"},
  {text:"Un trompo"},
  {text:"Los veinte años de ARENA"},
  {text:"Hacer berrinche"},
  {text:"Justicia por tu propia mano"},
  {text:"Sobrecompensar"},
  {text:"Bukkake pixelado"},
  {text:"Una vida de tristeza"},
  {text:"Racismo"},
  {text:"Lanzamiento de enanos"},
  {text:"Arcoíris y brillo del sol"},
  {text:"Un chango fumado"},
  {text:"Inundaciones repentinas"},
  {text:"Bolas"},
  {text:"Arcadas"},
  {text:"Empezar a cantar y bailar"},
  {text:"Los terroristas"},
  {text:"Lepra"},
  {text:"Britney Spears a los 55 años"},
  {text:"Glory hole"},
  {text:"Actitud"},
  {text:"Traer las luces"},
  {text:"El corazón de un niño"},
  {text:"La vagina de una anciana"},
  {text:"Un robot pequeñito"},
  {text:"Vender Avon"},
  {text:"Cachorritos!"},
  {text:"La mano peluda"},
  {text:"Regalar algo que te regalaron"},
  {text:"Despertar medio desnudo en un estacionamiento"},
  {text:"Escuchar activamente"},
  {text:"Esperarse hasta el matrimonio"},
  {text:"Autocanibalismo"},
  {text:"Condones"},
  {text:"Usar preservativo"},
  {text:"Limpieza étnica"},
  {text:"Estupidez incuantificable"},
  {text:"Parir al Anticristo"},
  {text:"Disfunción eréctil"},
  {text:"Mi colección de juguetes sexuales de alta tecnología"},
  {text:"El Papa"},
  {text:"Gente blanca"},
  {text:"Porno de tentáculos"},
  {text:"Vomitar a la vez que un grupo de arañas eclosionan en tu cerebro y salen por tus conductos lagrimales"},
  {text:"Hacer trampa en las Olimpiadas Especiales"},
  {text:"Lolis"},
  {text:"Demasiado gel de pelo"},
  {text:"Carisma"},
  {text:"Una miradita"},
  {text:"Suicidio"},
  {text:"Keanu Reeves"},
  {text:"Cagar para adentro"},
  {text:"Gays bailando quebradita"},
  {text:"Pedro Infante"},
  {text:"Menstruación"},
  {text:"Niños con cáncer en el trasero"},
  {text:"Una sorpresa salada"},
  {text:"Oriente medio"},
  {text:"La violación de nuestros derechos más básicos"},
  {text:"El Coronavirus"},
  {text:"Violar en una cita"},
  {text:"Ser fabuloso"},
  {text:"Necrofilia"},
  {text:"Centauros"},
  {text:"Sopa Maruchan"},
  {text:"Robot Hitler"},
  {text:"El verdadero significado de la Navidad"},
  {text:"Orinar una piedra de riñón"},
  {text:"El Tesoro del Saber"},
  {text:"Perras"},
  {text:"Cagar enchilado"},
  {text:"Estrógeno"},
  {text:"Un ano blanqueado"},
  {text:"Los negros"},
  {text:"Los que están muy discapacitados"},
  {text:"Otra maldita película de vampiros"},
  {text:"Unas pupusas recién hechas"},
  {text:"Michael Jackson"},
  {text:"Caballerosidad"},
  {text:"Huérfanos hermosos"},
  {text:"Tus audífonos enredados"},
  {text:"La cosa que te electrocuta los abdominales"},
  {text:"Mejoras cibernéticas"},
  {text:"Chavos que no te hablan después de la primera cita"},
  {text:"Calzones con rajita de canela"},
  {text:"Masturbación"},
  {text:"Hablar como fresa"},
  {text:"Pedos vaginales"},
  {text:"Esconder una erección"},
  {text:"Calzones comestibles"},
  {text:"Viagra"},
  {text:"Sopa muy caliente"},
  {text:"Tomar solo"},
  {text:"Allahu Akbar"},
  {text:"Dedos de pito"},
  {text:"¡Sexo Sorpresa!"},
  {text:"Múltiples heridas con navaja"},
  {text:"Una orden de tacos"},
  {text:"Hacerte popo"},
  {text:"Abuso infantil"},
  {text:"Perlas anales"},
  {text:"Muertes civiles"},
  {text:"Sacarla"},
  {text:"Robert Downey, Jr."},
  {text:"Carne de caballo"},
  {text:"Un sombrero muy chido"},
  {text:"Un vello púbico fuera de lugar"},
  {text:"Pandilleros fresas"},
  {text:"Pandilleros"},
  {text:"Metérsela por detrás"},
  {text:"Alimentar a un indigente"},
  {text:"Enseñarle a un robot a amar"},
  {text:"Unos vergazos"},
  {text:"Un molino lleno de cadáveres"},
  {text:"Hentai jodidamente extraño"},
  {text:"Una hielera llena de órganos"},
  {text:"Usar los calzones al revés para no lavarlos"},
  {text:"El sueño americano"},
  {text:"El rayo de la muerte"},
  {text:"Las papas del Wendy's"},
  {text:"Techo de espejo"},
  {text:"Cuando te echas un pedo y te cagas poquito"},
  {text:"Arrepentirse"},
  {text:"Italianos"},
  {text:"Amputados"},
  {text:"¿Abejas?"},
  {text:"Nazis"},
  {text:"Bebés muertos"},
  {text:"Un feto"},
  {text:"Eugenesia"},
  {text:"Novelas eróticas de Harry Potter"},
  {text:"200 gramos de heroína"},
  {text:"Prepucio"},
  {text:"Disparar un rifle al aire mientras se la metes hasta adentro a un cerdo que está chillando"},
  {text:"Mi estado de relación"},
  {text:"Universidad"},
  {text:"Stephen Hawking hablando sucio"},
  {text:"Solos de saxofón"},
  {text:"“Por zorra!”"},
  {text:"Emborracharte con enjuague bucal"},
  {text:"Padres muertos"},
  {text:"Permanencia del objeto"},
  {text:"Manos de sierra eléctrica"},
  {text:"Esnifar pegamento"},
  {text:"Mi vagina"},
  {text:"Preguntas de entrevista con sesgo racial"},
  {text:"Su majestad, la Reina Elizabeth II"},
  {text:"Pulgares opuestos"},
  {text:"Nicolas Cage"},
  {text:"Pantalones con un agujero en el trasero"},
  {text:"Una noche triste"},
  {text:"Exámenes de Admisión"},
  {text:"Como, lo que sea"},
  {text:"Concursos de belleza infantil"},
  {text:"Represión"},
  {text:"Un homicidio muy sucio"},
  {text:"Ser marginalizado"},
  {text:"No vacunar a los niños porque se es estúpido"},
  {text:"Parloteo"},
  {text:"Explosiones"},
  {text:"Rufies"},
  {text:"Dar el 110%"},
  {text:"Duendes"},
  {text:"Esperanza"},
  {text:"El Rev. Dr. Martin Luther King, Jr."},
  {text:"Un micropene"},
  {text:"Mi alma"},
  {text:"Una confusión caliente"},
  {text:"Complejo de Edipo"},
  {text:"Burritos"},
  {text:"Un condón defectuoso"},
  {text:"Vikingos"},
  {text:"Gansos"},
  {text:"Hacer pucheros"},
  {text:"Fanfict"},
  {text:"Gente ardiente"},
  {text:"Calentamiento global"},
  {text:"Atropellar a alguien"},
  {text:"Niños africanos"},
  {text:"Seducción"},
  {text:"Reggaeton"},
  {text:"Sufragio femenino"},
  {text:"Un incendio en una guardería"},
  {text:"Donald Trump"},
  {text:"Tiroteo masivo"},
  {text:"Asiáticos que no son buenos para las matemáticas"},
  {text:"Hombres japoneses viejitos"},
  {text:"Intercambiar cordialidades"},
  {text:"Heteronormatividad"},
  {text:"Partir el mar rojo"},
  {text:"Arnold Schwarzenegger"},
  {text:"Que te la chupen cuando manejas"},
  {text:"Abdominales"},
  {text:"espectaculares"},
  {text:"Pudín de higos"},
  {text:"Un león de zoológico triste"},
  {text:"Una bolsa de frijoles mágicos"},
  {text:"Malas decisiones de vida"},
  {text:"Una detonación termonuclear"},
  {text:"Mi vida sexual"},
  {text:"El clítoris"},
  {text:"Auschwitz"},
  {text:"Ahogando los niños en la bañera"},
  {text:"El Big Bang"},
  {text:"Una tortuga mordiéndote la puntita del pene"},
  {text:"Minas terrestres"},
  {text:"Amigos que se comen toda la botana"},
  {text:"Carne de ser humano"},
  {text:"Un mar de problemas"},
  {text:"Aumento de tamaño natural para el caballero"},
  {text:"Peleas sexys con almohadas"},
  {text:"Cabras comiendo latas"},
  {text:"Tiempo para mí mismo"},
  {text:"Sueños húmedos"},
  {text:"Ser un hechicero de putamadre"},
  {text:"Pelotas"},
  {text:"La Danza del Hada de Azúcar"},
  {text:"La voz de Morgan Freeman"},
  {text:"Piercings genitales"},
  {text:"La abuela"},
  {text:"Jalártela en una alberca llena de lágrimas de niños"},
  {text:"Decir Chistes del Holocausto en un mal momento"},
  {text:"Mujeres en comerciales de yogurt"},
  {text:"Trasvestis pasables"},
  {text:"Fricción"},
  {text:"Aguafiestas"},
  {text:"Una cama de agua"},
  {text:"La insensatez del hombre"},
  {text:"Pedorrearte e irte"},
  {text:"Morirse"},
  {text:"Hombres"},
  {text:"Ser pedante con los niños"},
  {text:"Herrores ortograficos"},
  {text:"¡Esta!"},
  {text:"Poner trampas en la casa para detener a los ladrones"},
  {text:"Los gays"},
  {text:"Huevos de Pterodáctilo"},
  {text:"Ejercicios para fomentar la sinergia del equipo"},
  {text:"Semana de parciales"},
  {text:"Tumor cerebral"},
  {text:"El lechero"},
  {text:"Cartas Contra la Humanidad"},
  {text:"Una boca sucia"},
  {text:"El miedo mismo"},
  {text:"Esperanza"},
  {text:"Tu hermana"},
  {text:"Nuestro dildo"},
  {text:"Jesús negro"},
  {text:"Cometer crímenes"},
  {text:"Pretender preocuparse"},
  {text:"Una papada sexy"},
  {text:"Bragas usadas"},
  {text:"Una crucifixión"},
  {text:"Ver a la abuela desnuda"},
  {text:"Siete muertos y tres en estado grave"},
  {text:"Niños"},
  {text:"El pasado"},
  {text:"Un abrazo"},
  {text:"Armas químicas"},
  {text:"Que se corran en ti"},
  {text:"Cometer suicidio"},
  {text:"Un pequeño niño que no se calla la puta boca sobre los dinosaurios"},
  {text:"Ejecutando un rehén cada hora"},
  {text:"El mismísimo demonio"},
  {text:"Vladimir Putin"},
  {text:"Memes"},
  {text:"Cometer traición"},
  {text:"Una bola de cera de oído, semen y pedazos de uña"},
  {text:"Zoofilia"},
  {text:"El orgasmo femenino"},
  {text:"La contraseña del wifi"},
  {text:"Algún chico"},
  {text:"Un trillón de dólares"},
  {text:"El patriarcado"},
  {text:"Lenguaje inclusivo"},
  {text:"Opresión femenina"},
  {text:"Una feminista con el cabello verde"},
  {text:"La comunidad LGBT"},
  {text:"Literalmente suplicando morir"},
]

const spaBlack = [
  {text:"Ahora se prohíbe _______ en los aviones.", whiteRequirement: 1},
  {text:"Es una pena que los niños de ahora se involucreen en _______.", whiteRequirement: 1},
  {text:"En 1,000 años, cuando el dinero en papel solo sea una lejana memoria lejana, _______ sera nuestra moneda nacional.", whiteRequirement: 1},
  {text:"¿Qué placer culpable tiene Bataman?", whiteRequirement: 1},
  {text:"El siguiente libro de J.K. Rowling: Harry Potter y la Cámara de _______.", whiteRequirement: 1},
  {text:"Asi es, maté a _______. ¿Cómo, preguntas? _______.", whiteRequirement: 2},
  {text:"Disculpe maestro, no acabé la tarea por _______.", whiteRequirement: 1},
  {text:"Y el Oscar a _______ va para _______.", whiteRequirement: 2},
  {text:"Para mi siguiente truco, sacaré un _______ de _______.", whiteRequirement: 2},
  {text:"_______ + _______ = _______.", whiteRequirement: 3},
  {text:"¿Qué traje de regreso de mis vacaciones?", whiteRequirement: 1},
  {text:"¿_______? Hay una aplicación para eso.", whiteRequirement: 1},
  {text:"Paso 1: _______. Paso 2: _______. Paso 3:  ¡Dinero!", whiteRequirement: 2},
  {text:"_______. ¡A que uno no te basta!", whiteRequirement: 1},
  {text:"¿Cuál es mi anti-droga?", whiteRequirement: 1},
  {text:"¡Presentamos X-treme baseball! es como baseball pero con _______.", whiteRequirement: 1},
  {text:"¿Cuál es mi poder secreto?", whiteRequirement: 1},
  {text:"¿Cuál es la nueva dieta maravilla?", whiteRequirement: 1},
  {text:"Viejo, no entres al baño, hay un _______ ahí adentro.", whiteRequirement: 1},
  {text:"Cuando el Faraón no reaccionó, Moisés invoco una plaga de _______.", whiteRequirement: 1},
  {text:"¿Como mantengo el fuego en mi relación amorosa?", whiteRequirement: 1},
  {text:"¿Qué es lo más crujiente?", whiteRequirement: 1},
  {text:"Cuando me drogue por primera vez, _______ se convirtió en _______.", whiteRequirement: 2},
  {text:"En la cárcel, dicen que puedes cambiar 200 cigarrillos por _______.", whiteRequirement: 1},
  {text:"¿Papi, porque mami está llorando?", whiteRequirement: 1},
  {text:"Santa Clos ahora les da _______ a los niños en vez de carbón.", whiteRequirement: 1},
  {text:"La vida de los indígenas cambio para siempre cuando los españoles les trajeron _______.", whiteRequirement: 1},
  {text:"Quizá lo trae de nacimiento. Quizá tiene _______.", whiteRequirement: 1},
  {text:"En sus últimos momentos Michael Jackson pensó en _______.", whiteRequirement: 1},
  {text:"A la gente blanca le gusta _______.", whiteRequirement: 1},
  {text:"_______ te lleva fácilmente a _______.", whiteRequirement: 2},
  {text:"¿Porque me duele todo?", whiteRequirement: 1},
  {text:"Una cena romántica a la luz de las velas no estaría completa sin _______.", whiteRequirement: 1},
  {text:"Si viajara al pasado, ¿que llevaría para convencer a la gente que soy un hechicero poderoso?", whiteRequirement: 1},
  {text:"Llame ya para adquirir un _______. Nuestras operadoras esperan su llamada.", whiteRequirement: 1},
  {text:"El viaje escolar quedo totalmente arruinado por _______.", whiteRequirement: 1},
  {text:"¿Cuál es el mejor amigo de una mujer? ", whiteRequirement: 1},
  {text:"Verá padre, estoy teniendo problemas con _______ y quisiera su consejo.", whiteRequirement: 1},
  {text:"Cuando sea presidente creare la secretaría de _______.", whiteRequirement: 1},
  {text:"¿Qué es lo que me ocultan mis papás?", whiteRequirement: 1},
  {text:"¿Qué es lo que nunca falla para animar las fiestas?", whiteRequirement: 1},
  {text:"En un mundo desolado por _______, nuestro único consuelo es _______.", whiteRequirement: 2},
  {text:"¡Ay no! ¡hay _______ en mi comida china!", whiteRequirement: 1},
  {text:"¡Acabo de ver este horrible video! Pls retweet!! #stop_______.", whiteRequirement: 1},
  {text:"Yo tomo para olvidar _______.", whiteRequirement: 1},
  {text:"_______ es bueno hasta la última gota.", whiteRequirement: 1},
  {text:"Ojalá no hubiera perdido el manual de _______.", whiteRequirement: 1},
  {text:"La medicina natural ahora utiliza los poderes curativos de _______.", whiteRequirement: 1},
  {text:"El nuevo reality de MTV se trata de 8 celebridades fracasadas viviendo con _______.", whiteRequirement: 1},
  {text:"¿Qué cosa le parecería perturbadora pero extrañamente encantadora a la abuela? ", whiteRequirement: 1},
  {text:"_______ ¡chócalas cuate! ", whiteRequirement: 1},
  {text:"No entendía bien _______ hasta que me tope con _______.", whiteRequirement: 2},
  {text:"Mientras tengo sexo, me gusta pensar en _______.", whiteRequirement: 1},
  {text:"¿Qué hizo que terminara mi relación anterior? ", whiteRequirement: 1},
  {text:"¿Qué es ese sonido? ", whiteRequirement: 1},
  {text:"_______. Así es como quiero morir?", whiteRequirement: 1},
  {text:"¿Por qué estoy tan pegajoso?", whiteRequirement: 1},
  {text:"¿Cuál es el siguiente juguete de la cajita feliz?", whiteRequirement: 1},
  {text:"¿De que cosa hay demasiado en el cielo?", whiteRequirement: 1},
  {text:"No sé con qué armas se peleará en la Tercera Guerra Mundial, pero la Cuarta Guerra Mundial se peleará con _______.", whiteRequirement: 1},
  {text:"¿Qué funciona siempre para ligar?", whiteRequirement: 1},
  {text:"No soy un doctor, pero estoy bastante seguro que sufres algo llamado “_______”.", whiteRequirement: 1},
  {text:"La rosa de Guadalupe presenta: _______, la historia de _______.", whiteRequirement: 2},
  {text:"_______: preferido por los niños, aprobado por las mamás.", whiteRequirement: 1},
  {text:"¿Por qué no puedo dormir en la noche?", whiteRequirement: 1},
  {text:"¿A que huele?", whiteRequirement: 1},
  {text:"¿Qué hace que me llene de gases?", whiteRequirement: 1},
  {text:"El mundo se va a acabar, el mundo se va a acabar, _______ es lo que nos va a matar.", whiteRequirement: 1},
  {text:"Próximamente, _______: El musical. ", whiteRequirement: 1},
  {text:"Los antropólogos han descubierto una tribu primitiva que venera _______.", whiteRequirement: 1},
  {text:"Antes de matarlo, Sr. Bond, déjeme mostrarle _______.", whiteRequirement: 1},
  {text:"Estudios revelan que las ratas encuentran la salida de un laberinto 50% más rápido después de ser expuestas a _______.", whiteRequirement: 1},
  {text:"A continuación, en ESPN2: El Campeonato Mundial de _______.", whiteRequirement: 1},
  {text:"Cuando sea millonario construiré una estatua de 20 metros que conmemore _______.", whiteRequirement: 1},
  {text:"Para atraer mas visitantes, el Museo Smithsoniano de Ciencias Naturales ha abierto una exhibición interactiva de _______.", whiteRequirement: 1},
  {text:"¡Guerra! ¿Para que sirve?", whiteRequirement: 1}
]

module.exports = {
  spaWhite,
  spaBlack
}